site_name:          Persian Web Toolkit
repo_url:           https://github.com/babakhani/PersianWebToolkit
theme:              'material'
site_description:   Persian Web Toolkit document
site_author:        babakhani.reza@gmail.com
copyright:          license http://www.wtfpl.net/
remote_branch: 'gh-pages'
docs_dir: 'src'
site_dir: 'docs'
site_url: 'http://babakhani.github.io/PersianWebToolkit/docs/'
repo_name: 'GitHub'
strict: true
edit_uri: PersianWebToolkit/docs/

google_analytics:
    - 'UA-40548780-1'
    - 'babakhani.github.io/PersianWebToolkit/'

extra_css:
    - //fonts.googleapis.com/css?family=Open+Sans
    - ./css/extra.css
    - ./lib/persian-datepicker/dist/css/persian-datepicker.css

markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - footnotes
  - meta
  - toc(permalink=true)

pages:
    - Persian Date:
        - Document: 'persian-date/index.md'
        - Change log: 'persian-date/changelog.md'
    - Persian Datepicker:
        - Getting Start: 'datepicker/index.md'
        - Example: 'datepicker/example.md'
        - Options: 'datepicker/options.md'
        - API: 'datepicker/api.md'
        - Change log: 'datepicker/changelog.md'

extra:
    social:
        - type: 'github'
          link: 'https://github.com/babakhani'
        - type: 'linkedin'
          link: 'https://de.linkedin.com/in/martin-donath-20a95039'

    logo: 'img/logo.svg'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'

    palette:
        primary: 'red'
        accent: 'blue light'
    version: 1.0
use_directory_urls: true
strict: true
dev_addr: '127.0.0.1:8000'
extra_javascript:
    - ./lib/jquery/dist/jquery.js
    - ./lib/persian-date/dist/persian-date.js
    - ./lib/persian-datepicker/dist/js/persian-datepicker.js
    - ./js/datepicker-example.js
    - ./js/doc.js
    - https://buttons.github.io/buttons.js